CREATE TABLE Sheet1(SELECT_* VARCHAR(10),Column_2 VARCHAR(10));
INSERT INTO Sheet1 (SELECT_*,Column_2) VALUES 
('       ( clicks / impressions ) * 100        AS CTR',''),
('       ( leads / clicks )                    AS Conv_1',''),
('       ( orders / leads )                    AS Conv_2',''),
('       ( revenue / orders )                  AS AOV',''),
('       ( mark_spent / clicks )               AS CPC',''),
('       ( mark_spent / orders )               AS CAC',''),
('       ( revenue - mark_spent ) / mark_spent AS ROMI',''),
('FROM   `marketing`',''),
('SELECT ( Sum(revenue) - Sum(mark_spent) ) / Sum(mark_spent)',''),
('FROM   `marketing`',''),
('SELECT ( ( Sum(revenue) - Sum(mark_spent) ) / Sum(mark_spent) )',''),
('FROM   `marketing`',''),
('WHERE  campaign_name = "instagram_blogger"',''),
('       AND c_date >= '2021-02-15'',''),
('       AND c_date <= '2021-02-25' ',''),
('       ',''),
('       ',''),
('SELECT Avg(revenue)',''),
('FROM   `marketing`',''),
('WHERE  Dayname(c_date) IN ( "sunday"',' "saturday" )'),
('SELECT Avg(revenue)',''),
('FROM   `marketing`',''),
('WHERE  Dayname(c_date) NOT IN ( "sunday"',' "saturday" )'),
('SELECT campaign_name',''),
('       campaign_id',''),
('       mark_spent',''),
('       impressions',''),
('       c_date',''),
('       leads',''),
('       revenue - mark_spent AS gross_profit',''),
('FROM   `marketing`',''),
('ORDER  BY gross_profit',''),
('          impressions DESC;',''),
('          ',''),
('          ',''),
('SELECT Sum(mark_spent)',''),
('FROM   `marketing`',''),
('WHERE  ( revenue - mark_spent ) / mark_spent < 0',''),
('       AND Locate('facebook'',' campaign_name) ');