CREATE TABLE Sheet1(1_select_video_id VARCHAR(10),title VARCHAR(10),country VARCHAR(10),count_trending_date_as_no_of_days_trended_from_yt_trending_videos_group_by_title VARCHAR(10),video_id VARCHAR(10),country VARCHAR(10),Column_7 VARCHAR(10),Column_8 VARCHAR(10),Column_9 VARCHAR(10),Column_10 VARCHAR(10),Column_11 VARCHAR(10),Column_12 VARCHAR(10),Column_13 VARCHAR(10),Column_14 VARCHAR(10),Column_15 VARCHAR(10));
INSERT INTO Sheet1 (1_select_video_id,title,country,count_trending_date_as_no_of_days_trended_from_yt_trending_videos_group_by_title,video_id,country,Column_7,Column_8,Column_9,Column_10,Column_11,Column_12,Column_13,Column_14,Column_15) VALUES 
('select count(*) from (select video_id','title','country','count(trending_date) as no_of_days_trended from yt_trending_videos where country="US" group by title','video_id having no_of_days_trended > 5) a','','','','','','','','','',''),
('(2) select video_id','title','snippettitle','count(trending_date) as no_of_days_trended from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id group by title','video_id','snippettitle','','','','','','','','',''),
('select snippettitle','avg(no_of_days_trended) Average from ( select video_id','title','snippettitle','count(trending_date) as no_of_days_trended from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id group by title','video_id','snippettitle)a group by snippettitle order by Average desc','','','','','','','',''),
('(3) select dayname(trending_date) day','snippettitle','count(distinct video_id) no_of_videos from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id group by snippettitle','day having day not in ("Saturday"','Sunday) order by snippettitle','','','','','','','','','',''),
('select snippettitle','count(distinct video_id) no_of_videos from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id where dayname(trending_date) not in ("Saturday"','Sunday) and snippettitle='Music' group by snippettitle','','','','','','','','','','','',''),
('(4) select snippettitle as category_title','country','sum(totalviews) total_views','sum(totallikes) total_likes','avg(no_of_days_trended) avg_trending_days from (select snippettitle','video_id','title','sum(views) totalviews','sum(likes) totallikes','country','count(trending_date) as no_of_days_trended from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id group by title','video_id','country','snippettitle)a group by snippettitle','country'),
(' ','','','','','','','','','','','','','',''),
('select snippettitle as category_title','country','sum(totalviews) total_views','sum(totallikes) total_likes','avg(no_of_days_trended) avg_trending_days from (select snippettitle','video_id','title','sum(views) totalviews','sum(likes) totallikes','country','count(trending_date) as no_of_days_trended from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id group by title','video_id','country','snippettitle)a group by snippettitle','country having category_title='Sports' and country='Canada''),
('(5) select country','count(title) no_of_videos  from (select video_id','title','country','sum(views) total_views','sum(likes) total_likes','dense_rank() over(partition by country order by sum(views) desc) rank_view','dense_rank() over(partition by country order by sum(likes) desc) rank_like from yt_trending_videos group by video_id','title','country)a where rank_view <= 20 and rank_like <= 20 group by country order by no_of_videos desc','','','','',''),
('select category_title','avg(rating) from (select *','Round((( views - min_views ) * 100 ) / (max_views - min_views)','0)   as rating from (select video_id','title','snippettitle as category_title','views','max(views) over(partition by snippettitle) max_views','min(views) over(partition by snippettitle) min_views from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id order by category_title desc)a)b group by category_title','','','','','',''),
('(6) select *','Round((( views - min_views ) * 100 ) / (max_views - min_views)','0)   as rating from (select video_id','title','snippettitle as category_title','views','max(views) over(partition by snippettitle) max_views','min(views) over(partition by snippettitle) min_views from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id ) a','','','','','','',''),
('select category_title','avg(rating) from( select *','Round((( likes - min_likes ) * 100 ) / (max_likes - min_likes)','0)   as rating from (select video_id','title','snippettitle as category_title','likes','max(likes) over(partition by snippettitle) max_likes','min(likes) over(partition by snippettitle) min_likes from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id ) a )b group by category_title order by avg(rating) desc','','','','','',''),
('(7) select *','Round((( likes - min_likes ) * 100 ) / (max_likes - min_likes)','0)   as rating from (select video_id','title','snippettitle as category_title','likes','max(likes) over(partition by snippettitle) max_likes','min(likes) over(partition by snippettitle) min_likes from yt_trending_videos A JOIN yt_category_map B ON A.category_id=B.id ) a ','','','','','','','');