CREATE TABLE Sheet1(select_count_DISTINCT_Item_Category_from_Item VARCHAR(10),Column_2 VARCHAR(10),Column_3 VARCHAR(10),Column_4 VARCHAR(10),Column_5 VARCHAR(10),Column_6 VARCHAR(10));
INSERT INTO Sheet1 (select_count_DISTINCT_Item_Category_from_Item,Column_2,Column_3,Column_4,Column_5,Column_6) VALUES 
('select count(DISTINCT couponType) from CouponMapping','','','','',''),
('select count(DISTINCT state) from CityData','','','','',''),
('select count(DISTINCT OrderType) from CustomerTransactionData','','','','',''),
('select year(PurchaseDate) 'year'','month(PurchaseDate) 'months'','count(Trans_Id) from CustomerTransactionData GROUP by year(PurchaseDate)','month(PurchaseDate) order by count(Trans_Id) desc','',''),
('select b.Item_Category','sum(PurchasingAmt)  from CustomerTransactionData a join Item b on a.Item_Id=b.Item_Id GROUP by Item_Category order by sum(PurchasingAmt) desc','','','',''),
('select year(PurchaseDate) 'year'','quarter(PurchaseDate) 'quarter'','sum(PurchasingAmt) from CustomerTransactionData GROUP by year(PurchaseDate)','quarter(PurchaseDate) order by sum(PurchasingAmt) desc','',''),
('select OrderType','sum(PurchasingAmt) from CustomerTransactionData GROUP by OrderType order by sum(PurchasingAmt) desc','','','',''),
('select CityTier','sum(PurchasingAmt) from CustomerTransactionData a join Customer b on a.Cust_Id=b.customer_id join CityData c on b.City_Id=c.City_Id GROUP by CityTier order by sum(PurchasingAmt) desc','','','',''),
('select count(DISTINCT Trans_Id) from CustomerTransactionData where campaign_id is not null','','','','',''),
('select count(*) from ','','','','',''),
('(select DISTINCT first_value(PurchasingAmt) over(partition by Cust_Id order by PurchaseDate) from CustomerTransactionData where coupon_id is null and campaign_id is null)a','','','','',''),
('select count(*) from ','','','','',''),
('(select DISTINCT first_value(PurchasingAmt) over(partition by Cust_Id order by PurchaseDate) from CustomerTransactionData)a','','','','',''),
('select DISTINCT count(Cust_Id) from CustomerTransactionData  where coupon_id is null and campaign_id is null','','','','',''),
('select sum(PurchasingAmt) from CustomerTransactionData where campaign_id is not null','','','','',''),
('select sum(PurchasingAmt) from CustomerTransactionData where campaign_id is null and coupon_id is null','','','','',''),
('select sum(PurchasingAmt) from CustomerTransactionData where coupon_id is not null and campaign_id is null','','','','',''),
('select year(PurchaseDate)','sum(quantity)','sum(PurchasingAmt) from CustomerTransactionData GROUP by year(PurchaseDate) order by year(PurchaseDate) ','','',''),
('select year(PurchaseDate)','count(DISTINCT Cust_Id) from CustomerTransactionData GROUP by  year(PurchaseDate) order by year(PurchaseDate) ','','','',''),
('select OrderType','count(Cust_Id) from CustomerTransactionData GROUP by OrderType Order by count(Cust_Id) desc','','','',''),
('select year(PurchaseDate)','campaignType','sum(PurchasingAmt) from CustomerTransactionData a join Campaign b on a.campaign_id=b.campaign_id GROUP by campaignType','year(PurchaseDate) Order by year(PurchaseDate) asc','sum(PurchasingAmt) desc',''),
('select Concat(oneitem',' , ','twoitem)','count(*) from ','',''),
('(SELECT C1.Cust_Id 'cust'','C1.OrderType',' C1.PurchaseDate AS PurchaseDate1',' C2.PurchaseDate AS PurchaseDate','C1.item_id 'oneitem'','count(C1.item_id)  '),
('over(partition by C1.Cust_Id Order by C1.item_id) 'one'','C2.item_id 'twoitem'','count(C2.item_id) over(partition by C1.Cust_Id Order by C2.item_id) 'two' ','','',''),
('FROM CustomerTransactionData AS C1 INNER JOIN CustomerTransactionData AS C2 ON C1.Cust_Id = C2.Cust_Id ','','','','',''),
('WHERE C1.Trans_Id != C2.Trans_Id AND C1.OrderType = C2.OrderType AND C1.item_id != C2.item_id )a where OrderType='Household' GROUP by oneitem','twoitem order by count(*) desc','','','','');