CREATE TABLE Sheet1(select_date VARCHAR(10),sum_sale_amt_as_total_from_sales_fact_group_by_date_order_by_total_desc VARCHAR(10),Column_3 VARCHAR(10),Column_4 VARCHAR(10));
INSERT INTO Sheet1 (select_date,sum_sale_amt_as_total_from_sales_fact_group_by_date_order_by_total_desc,Column_3,Column_4) VALUES 
('select category_desc','sum(sale_amt) from category_dim a JOIN sales_fact b on a.product_id=b.product_id where category_desc='Dairy' group by category_desc','',''),
('select city','sum(sale_amt) from geography_dim a JOIN sales_fact b ON a.store_id=b.store_id group by city order by sum(sale_amt) desc','',''),
('select Customer_ID','sum(priceusd*quantity) as total from sales_fact  group by Customer_ID having total<3000','',''),
('select count(*)  from sales_fact  having sum(priceusd*quantity)<3000','','',''),
('select sum(sale_amt) from geography_dim a join sales_fact b on a.store_id=b.store_id join category_dim c on  b.product_id=c.product_id where category_desc='Cereals' and city='Bangalore'','','',''),
('select category_desc','sum(sale_amt) from  geography_dim a join sales_fact b on a.store_id=b.store_id join category_dim c on  b.product_id=c.product_id where city='Mumbai' group by category_desc order by sum(sale_amt) desc','',''),
('select transaction_id','(priceusd*quantity) as total','category_desc from category_dim a join sales_fact b on a.product_id=b.product_id where category_desc='Drinks & Bevrages'  ',''),
('select sum(quantity*priceusd)/count(Customer_ID) from sales_fact a join geography_dim b on a.store_id=b.store_id where city='Chennai'','','',''),
('select sum(sale_amt) from sales_fact','','',''),
('select count(Customer_ID) from sales_fact','','',''),
('select a.Customer_ID','sum(sale_amt)/count(a.product_id) as total from sales_fact a join  category_dim b on a.product_id=b.product_id group by a.Customer_ID','a.product_id order by total desc',''),
('select count(*) from (select product_id','count(Customer_ID)','state as customers from sales_fact a join geography_dim b on a.store_id=b.store_id where state='Maharashtra'  group by product_id having count(Customer_ID)>=5 order by count(Customer_ID) desc) a',''),
('select a.product_id','a.product_desc','count(b.Customer_ID) from category_dim a left join sales_fact b on a.product_id=b.product_id group by a.product_id','a.product_desc order by count(b.Customer_ID) desc'),
('select count(*) from (select city','sum(sale_amt)/count(distinct Customer_ID) as rev from sales_fact a join geography_dim b on a.store_id=b.store_id group by city having rev < 3500 order by rev desc) a','',''),
('select count(*) from (select Customer_ID','sum(sale_amt)','state from sales_fact a join geography_dim b on a.store_id=b.store_id where state='Karnataka' group by Customer_ID having sum(sale_amt)<3000 ) a',''),
('select sum(sale_amt)/count(distinct Customer_ID) from sales_fact a join geography_dim b on a.store_id=b.store_id where state='Maharashtra'','','',''),
('select product_desc','category_desc','sum(sale_amt) from sales_fact a join category_dim b on a.product_id=b.product_id where category_desc='Cereals' group by product_desc order by sum(sale_amt)',''),
('select sum(sale_amt)/count(distinct Customer_ID) from sales_fact a join geography_dim b on a.store_id=b.store_id where city='Chennai'','','',''),
('select count(*) from (select Customer_ID','sum(sale_amt) from sales_fact group by Customer_ID having sum(sale_amt)<3000) a','',''),
('select Customer_ID','sum(sale_amt)/count(distinct product_id) as sum from sales_fact group by Customer_ID order by sum desc','',''),
('select a.transaction_id','sum(a.sale_amt)','b.category_desc from sales_fact a join category_dim b on  a.product_id=b.product_id where category_desc='Drinks & Bevrages' group by transaction_id order by sum(a.sale_amt) desc',''),
('select transaction_id','sum(sale_amt)/sum(quantity) as sales from sales_fact group by  transaction_id order by sales desc','','');